# render.yaml
services:
  - type: web
    name: backend-render
    env: node
    plan: free
    buildCommand: "npm install"
    startCommand: "npm start"
    envVars:
      - key: PORT
        value: 8080
